version: '3.8'

# -----------------------------------------
# SERVICES
# -----------------------------------------

services:
  # -----------------------------------------
  # MariaDB (Database Service)
  # -----------------------------------------
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    ports:
      - "3306:3306"  # Exposing MySQL database port
    env_file:
      - .env
    restart: unless-stopped  # Restart only if it crashes
    environment:
      MDB_PW: /run/secrets/mdb_pw
      MDB_ROOT_PW: /run/secrets/mdb_root_pw
    secrets:
      - mdb_pw
      - mdb_root_pw
    networks:
      - my_network
    volumes:
      - mariadb:/var/lib/mysql  # Persistent database storage

  # -----------------------------------------
  # WordPress (Application Service)
  # -----------------------------------------
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb  # Ensures MariaDB is running before WordPress starts
    restart: unless-stopped
    environment:
      MDB_PW: /run/secrets/mdb_pw
      WP_ADMIN_PW: /run/secrets/wp_admin_pw
      WP_USER_PW: /run/secrets/wp_user_pw
    secrets:
      - mdb_pw
      - wp_admin_pw
      - wp_user_pw
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/wordpress  # Persistent storage for WordPress data

  # -----------------------------------------
  # Nginx (Web Server & Reverse Proxy)
  # -----------------------------------------
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"  # HTTPS
    env_file:
      - .env
    depends_on:
      - wordpress  # Ensures WordPress is running before Nginx starts
    restart: unless-stopped
    networks:
      - my_network
    volumes:
      - wordpress:/var/www/wordpress  # Serve WordPress files
      - ../secrets/inception.crt:/etc/nginx/ssl/inception.crt  # SSL Certificate
      - ../secrets/inception.key:/etc/nginx/ssl/inception.key  # SSL Key

# -----------------------------------------
# NETWORKS
# -----------------------------------------

networks:
  my_network:

# -----------------------------------------
# VOLUMES (Persistent Storage)
# -----------------------------------------

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/ekechedz/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/ekechedz/data/wordpress
      o: bind
      type: none

# -----------------------------------------
# SECRETS (Securely Store Sensitive Data)
# -----------------------------------------

secrets:
  mdb_pw:
    file: ../secrets/db_password.txt
  mdb_root_pw:
    file: ../secrets/db_root_password.txt
  wp_admin_pw:
    file: ../secrets/wp_root_password.txt
  wp_user_pw:
    file: ../secrets/wp_user_password.txt
